title: unapologetic thoughts, please! # name of the site
author: Igor Lima # name of site's author
email: lima.igorribeiro@gmail.com # email of site's author

url: https://igorlima.github.io/unapologetic-thoughts # root address of the site
baseurl: "/unapologetic-thoughts" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  A (nearly) no-CSS, fast, minimalist Jekyll theme.

# https://jekyllrb.com/docs/permalinks/
# permalink: /:slug.html
permalink: /:categories/:year/:month/:day/:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

# https://github.com/jekyll/jekyll-feed
feed:
  posts_limit: 1000

plugins:
  - jekyll-feed
  - jekyll-seo-tag
